# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  nuget-azure-artifacts:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/jjohanning0798/PartsUnlimited/_packaging/nuget-example/nuget/v3/index.json
    token: ':${{ secrets.AZURE_DEVOPS_PAT }}'
    # username: jjohanning0798
    # password: ${{ secrets.AZURE_DEVOPS_PAT }}  # Must be an unencoded password
updates:
  - package-ecosystem: "nuget"
    directory: "/Examples/HostedCommandsBot/"
    registries:
      - nuget-azure-artifacts
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
